Repository functionless/functionless, pull requests merged in 2022-08, with the labels that each got.

#375 feat: add QuasiString NodeKind for representing quasi strings in a TemplateExpr
  src/asl.ts
  src/checker.ts
  src/compile.ts
  src/event-bridge/target-input.ts
  src/event-bridge/utils.ts
  src/expression.ts
  src/guards.ts
  src/node-ctor.ts
  src/node-kind.ts
  src/node.ts
  src/util.ts
  src/vtl.ts
Labels: abstract-syntax-tree

#381 feat: remove PromiseExpr and PromiseArrayExpr
  src/api.ts
  src/appsync.ts
  src/asl.ts
  src/compile.ts
  src/event-bridge/target-input.ts
  src/expression.ts
  src/guards.ts
  src/integration.ts
  src/node-ctor.ts
  src/node-kind.ts
  src/vtl.ts
Labels: abstract-syntax-tree

#382 feat: add isAsync and isAsterisk to function expressions and isOptional to ElementAccessExpr
  src/asl.ts
  src/assert.ts
  src/compile.ts
  src/declaration.ts
  src/ensure.ts
  src/event-bridge/utils.ts
  src/expression.ts
  src/node-kind.ts
  src/node.ts
  src/step-function.ts
  src/vtl.ts
  test/node.test.ts
Labels: abstract-syntax-tree

#387 feat(event-bridge): Add `trace-header` field to `Event` type
  src/event-bridge/event-bus.ts
  test/__snapshots__/step-function.test.ts.snap
  test/function.localstack.test.ts
  test/step-function.test.ts
Labels: event-bridge

#389 feat: add isAwait to ForOfStmt and isRest to ParameterDecl, fix TemplateExpr
  src/api.ts
  src/appsync.ts
  src/asl.ts
  src/compile.ts
  src/declaration.ts
  src/error-code.ts
  src/event-bridge/event-pattern/synth.ts
  src/event-bridge/target-input.ts
  src/event-bridge/utils.ts
  src/expression.ts
  src/guards.ts
  src/node-ctor.ts
  src/node-kind.ts
  src/node.ts
  src/statement.ts
  src/step-function.ts
  src/util.ts
  src/validate.ts
  src/visit.ts
  src/vtl.ts
  test-app/src/message-board.ts
  test/__snapshots__/step-function.localstack.test.ts.snap
  test/__snapshots__/step-function.test.ts.snap
  test/__snapshots__/vtl.test.ts.snap
  test/appsync.test.ts
  test/eventpattern.test.ts
  test/reflect.test.ts
  test/step-function.test.ts
  test/vtl.test.ts
Labels: abstract-syntax-tree

#386 feat: replace ts-transformer with SWC transformer
  .gitattributes
  .gitignore
  .projen/deps.json
  .projen/files.json
  .projen/tasks.json
  .projenrc.js
  .swcrc
  CONTRIBUTING.md
  package.json
  src/appsync.ts
  src/asl.ts
  src/aws.ts
  src/compile.ts
  src/function.ts
  src/integration.ts
  src/reflect.ts
  src/visit.ts
  test-app/.swcrc
  test-app/cdk.json
  test-app/package.json
  test-app/yarn.lock
  test/__snapshots__/serialize.test.ts.snap
  test/__snapshots__/step-function.localstack.test.ts.snap
  test/function.localstack.test.ts
  test/isolated.test.ts
  test/reflect.test.ts
  test/validate.test.ts
  tsconfig.dev.json
  website/docs/getting-started.md
  yarn.lock
Labels: abstract-syntax-tree

#403 fix: enforce YieldExpr.expr is defined for yield*
  src/expression.ts
Labels: abstract-syntax-tree

#404 feat: add Span information to F-AST
  .projen/deps.json
  .projen/tasks.json
  .projenrc.js
  package.json
  src/api.ts
  src/appsync.ts
  src/asl.ts
  src/compile.ts
  src/declaration.ts
  src/error.ts
  src/event-bridge/utils.ts
  src/expression.ts
  src/integration.ts
  src/node.ts
  src/s-expression.ts
  src/span.ts
  src/statement.ts
  src/visit.ts
  test-app/yarn.lock
  test/node.test.ts
  yarn.lock
Labels: abstract-syntax-tree

#409 feat: add filename to root AST nodes
  src/declaration.ts
  src/expression.ts
Labels: abstract-syntax-tree

#410 feat(ast): update ClassDecl.name and ClassExpr.name to be an Identifier
  src/compile.ts
  src/declaration.ts
  src/expression.ts
Labels: abstract-syntax-tree

#419 feat(user-pool): add a UserPool Construct with type-safe triggers
  src/function.ts
  src/index.ts
  src/secret.ts
  src/user-pool.ts
  test/user-pool.test.ts
  website/docs/concepts/integration/index.md
  website/docs/concepts/user-pool.md
Labels: auth

#449 fix(step-functions): compare undefined and null
  src/asl/asl-graph.ts
  src/asl/synth.ts
  test/__snapshots__/step-function.localstack.test.ts.snap
  test/__snapshots__/step-function.test.ts.snap
  test/step-function.localstack.test.ts
Labels: step-functions

#453 fix: upgrade to latest SWC compatible with new swc_core
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  test-app/package.json
  test-app/yarn.lock
  yarn.lock
Labels: abstract-syntax-tree
