Repository functionless/functionless, pull requests merged in 2022-09, with the labels that each got.

#428 feat(sqs): implement Queue Construct with forEach capability
  .vscode/launch.json
  src/asl/asl-graph.ts
  src/declaration.ts
  src/error-code.ts
  src/event-bridge/event-bus.ts
  src/event-bridge/rule.ts
  src/event-bridge/transform.ts
  src/event-source.ts
  src/function-prewarm.ts
  src/function.ts
  src/index.ts
  src/integration.ts
  src/iterable.ts
  src/queue.ts
  src/reflect.ts
  src/serializer.ts
  src/statement.ts
  src/table.ts
  src/util.ts
  test-app/.swcrc
  test-app/cdk.json
  test-app/hook.js
  test-app/src/order-processing-queue.ts
  test-app/src/stream-processing.ts
  test-app/src/text-processing-queue.ts
  test-app/tsconfig.json
  test/__snapshots__/step-function.test.ts.snap
  test/__snapshots__/validate.test.ts.snap
  test/queue.localstack.test.ts
  test/runtime.ts
  test/step-function.test.ts
  test/test-files/step-function.ts
  website/docs/concepts/event-source.md
  website/docs/concepts/iterable.md
  website/docs/concepts/queue.md
  yarn.lock
Labels: sqs

#494 fix: ForOfStmt, ForInStmt, ForStmt, WhileStmt, DoStmt ES conformance
  src/api.ts
  src/appsync.ts
  src/asl/synth.ts
  src/declaration.ts
  src/expression.ts
  src/integration.ts
  src/node.ts
  src/span.ts
  src/statement.ts
  src/vtl.ts
Labels: abstract-syntax-tree

#465 chore(docs): getting started rework
  website/docs/concepts/terminology.md
  website/docs/getting-started.md
  website/docs/getting-started/_category_.yml
  website/docs/getting-started/assets/confirm-destroy.png
  website/docs/getting-started/assets/deployment-confirmation.png
  website/docs/getting-started/assets/iam-review.png
  website/docs/getting-started/assets/stack-destroyed.png
  website/docs/getting-started/assets/synth-success.png
  website/docs/getting-started/clean-up.mdx
  website/docs/getting-started/create-new-project.mdx
  website/docs/getting-started/deploy-project.mdx
  website/docs/getting-started/project-walkthrough.md
  website/docs/getting-started/setup.md
  website/package.json
  website/src/components/screenshot.tsx
  website/src/pages/index.tsx
  website/tsconfig.json
  website/yarn.lock
Labels: documentation

#499 chore: remove backwards compatible VariableDecl in ForOfStmt and ForInStmt
  .projen/deps.json
  .projenrc.ts
  package.json
  src/asl/synth.ts
  src/statement.ts
  src/vtl.ts
  test-app/yarn.lock
  yarn.lock
Labels: abstract-syntax-tree

#468 feat(step-functions): support and utilize new intrinsics
  .eslintrc.json
  .projen/tasks.json
  .projenrc.ts
  src/asl/asl-graph.ts
  src/asl/synth.ts
  src/checker.ts
  src/error-code.ts
  src/queue.ts
  src/step-function.ts
  src/validate.ts
  test/__snapshots__/step-function.localstack.test.ts.snap
  test/__snapshots__/step-function.test.ts.snap
  test/__snapshots__/validate.test.ts.snap
  test/runtime.ts
  test/step-function.localstack.test.ts
  test/step-function.test.ts
  test/test-files/step-function.ts
  test/validate.test.ts
  website/docs/concepts/step-function/usage.md
Labels: step-functions

#515 feat(step-functions): object spread and fix bind in SFN map/foreach
  src/asl/asl-graph.ts
  src/asl/synth.ts
  src/queue.ts
  src/step-function.ts
  test/__snapshots__/serialize.test.ts.snap
  test/__snapshots__/step-function.localstack.test.ts.snap
  test/__snapshots__/step-function.test.ts.snap
  test/step-function.localstack.test.ts
  test/step-function.test.ts
  test/test-files/step-function.ts
Labels: step-functions

#518 feat(step-functions): task utility
  .projen/tasks.json
  .projenrc.ts
  package.json
  src/asl/asl-graph.ts
  src/asl/states.ts
  src/asl/synth.ts
  src/node.ts
  src/step-function.ts
  src/visit.ts
  test/__snapshots__/appsync.test.ts.snap
  test/__snapshots__/serialize.test.ts.snap
  test/__snapshots__/step-function.localstack.test.ts.snap
  test/__snapshots__/step-function.test.ts.snap
  test/step-function.localstack.test.ts
  test/tsconfig.json
  test/util.ts
Labels: step-functions

#519 feat(dynamodb): deprecate $AWS.DynamoDB, add methods to Table instance
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  src/appsync.ts
  src/aws.ts
  src/error-code.ts
  src/function-prewarm.ts
  src/function.ts
  src/table.ts
  src/table/appsync.ts
  src/table/batch-get-item.ts
  src/table/batch-write-item.ts
  src/table/delete-item.ts
  src/table/get-item.ts
  src/table/index.ts
  src/table/integration.ts
  src/table/put-item.ts
  src/table/query.ts
  src/table/return-value.ts
  src/table/runtime.ts
  src/table/scan.ts
  src/table/table.ts
  src/table/transact-get-item.ts
  src/table/transact-write-item.ts
  src/table/update-item.ts
  src/table/util.ts
  src/tsc.ts
  src/validate.ts
  test-app/src/api-test.ts
  test-app/src/message-board.ts
  test-app/src/people-db.ts
  test-app/src/stream-processing.ts
  test/__snapshots__/serialize-closure.test.ts.snap
  test/__snapshots__/serialize.test.ts.snap
  test/__snapshots__/step-function.localstack.test.ts.snap
  test/__snapshots__/step-function.test.ts.snap
  test/__snapshots__/validate.test.ts.snap
  test/api.test.ts
  test/appsync.test.ts
  test/eventbus.localstack.test.ts
  test/function.localstack.test.ts
  test/function.test.ts
  test/queue.localstack.test.ts
  test/runtime.ts
  test/serialize-closure.test.ts
  test/serialize.test.ts
  test/step-function.localstack.test.ts
  test/step-function.test.ts
  test/table.runtime.gql
  test/table.runtime.test.ts
  test/table.test.ts
  test/test-files/api-gateway.ts
  test/test-files/appsync.ts
  test/test-files/function.ts
  test/test-files/step-function.ts
  test/validate.test.ts
  website/docs/concepts/table.md
  yarn.lock
Labels: dynamo
